Desktop version branch
DiegoMero/my-portfolio pull request #13
Opened 2022-06-02 22:24 UTC by DiegoMero

This pull request is to add the desktop version of the portfolio.

2022-06-02 22:59 UTC, omarsalem7 requested changes
Hi @DiegoMero, 

Good job so far! 👏
You have done well reaching this point of the milestone, but there are some issues that you still need to work on to go to the next project but you are almost there! 

![you-are-near](https://media.giphy.com/media/SSR17K6yZWvGCYrfUh/giphy.gif)

## Highlights
- Descriptive pull request ✔️
- No linter errors ✔️
- Descriptive commit messages ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-02 22:59 UTC, omarsalem7 commented on styles.css
> +  }
- [ ] Consider fixing the extra right space in your design and also fix it in the mobile version
- your design 
![image](https://user-images.githubusercontent.com/53402600/171750859-1f6acda1-e5fc-434a-8fec-d5be8ab97de5.png)

- [ ] [OPTIONAL] You are using fixed units for width `px`, I recommend you not give fixed units to not make extra spaces in your design like the above image. You can refer to this [guideline](https://web.dev/responsive-web-design-basics/) to make your design responsive and I recommend using flexbox and grid to lay out the elements on the page.

2022-06-02 22:59 UTC, omarsalem7 commented on index.html
> +        <img class="ellipse-8desktop" src="images/Ellipse8desktop.png" alt="Ellipse">
- [ ] Kindly use `background-image` instead of extracting all images and putting them like this to make your code clear, you can refer to it from [here](https://www.w3schools.com/cssref/pr_background-image.asp)

2022-06-03 05:43 UTC, elmar8287 requested changes
Hi, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-03 05:43 UTC, elmar8287 commented on index.html
> +        <div class="headline">
- [ ] Please, consider the suggestion from the previous review regarding fixing the right space both on desktop and mobile versions. 

> Desktop version: You can see here the background is repeating
<img width="1384" alt="Screen Shot 2022-06-03 at 09 28 14" src="https://user-images.githubusercontent.com/49064106/171793071-a91ab24e-0a59-4e49-ac23-746ff37dfef0.png">

> Mobile version: here you can see the horizontal scrolling.
![2022-06-03 09 33 32](https://user-images.githubusercontent.com/49064106/171793151-7c9f87dd-516e-4b7f-8f01-6f23a65cb704.gif)

2022-06-03 05:43 UTC, elmar8287 commented on index.html
>                  <li>
- [ ] [OPTIONAL] - Please, consider fixing the input border style - try to remove the borders, to make it close to the original design.

> You version
<img width="610" alt="Screen Shot 2022-06-03 at 09 28 45" src="https://user-images.githubusercontent.com/49064106/171793475-274242b5-5df1-43e0-92f1-3c6874dc677f.png">

> Figma design
<img width="381" alt="Screen Shot 2022-06-03 at 09 40 58" src="https://user-images.githubusercontent.com/49064106/171793678-2b97b9b0-7927-490d-a16f-e16b8ff4e35d.png">

- [ ] [OPTIONAL] Please, try to give the background for the navigation section, it is transparent and while scrolling the page, it makes it difficult to read the content 👍 
![2022-06-03 09 32 38](https://user-images.githubusercontent.com/49064106/171793999-2b34b3fd-9abd-46bf-b4f7-d22f45f7c3b3.gif)

2022-06-03 06:01 UTC, DiegoMero commented on index.html
> +        <div class="headline">
Hello, do you know how to fix the right space on the mobile version?

2022-06-03 06:53 UTC, micheaol approved these changes
# STATUS: APPROVED :green_circle: :clap: 

Hi @DiegoMero , 

Great work on making the changes requested by the previous reviewers 👏 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## TO HIGHLIGHT: 
- Your project is professional 💯 
- Your repo is professional 💯 
- Well structured files 💯 
- You set up linter files and no errors. 💯 

![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-03 06:56 UTC, merged